# This workflow takes a previously-built PR copy of the game
# and uploads it to Netlify as a preview deployment,
# also dropping a link to that deploy into the PR comments
#
# See https://securitylab.github.com/research/github-actions-preventing-pwn-requests
# for context why this is two workflows instead of one.

name: Test and Deploy PRs

on:
  workflow_run:
    workflows: [Build PR]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Download build artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{ github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));

      - name: Unzip artifact
        run: unzip pr.zip; rm pr.zip

      - name: Store PR info in ENV
        run: |
          PR_NUMBER=$(cat pr_number)
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          rm pr_number
          PR_TITLE=$(cat pr_title)
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
          rm pr_title
          PR_SENDER=$(cat pr_sender)
          echo "PR_SENDER=$PR_SENDER" >> $GITHUB_ENV
          rm pr_sender
          PR_ACTION=$(cat pr_action)
          echo "PR_ACTION=$PR_ACTION" >> $GITHUB_ENV
          rm pr_action

      - name: Netlify preview deploy
        uses: nwtgck/actions-netlify@v1.2
        id: netlify-deploy
        with:
          publish-dir: '.'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Test your proposed changes!'
          alias: pr-${{ env.PR_NUMBER }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: 'Comment on PR with link to preview'
        uses: actions/github-script@v3
        with:
          script: |
            var fs = require('fs');
            var issue_number = process.env.PR_NUMBER
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: 'Please view and test your changes at this site: ðŸ‘‰ ${{steps.netlify-deploy.outputs.deploy-url}} ðŸ‘ˆ'
            });

